<#
    Relay-Setup.ps1 - RelayMCP setup and repair for this Windows handheld. Safe to run any time, anywhere: each step
    checks first and only fixes what is missing. Double-tap "Setup RelayMCP.cmd" (or the "Repair RelayMCP" shortcut).

    At home (a network whose router is listed in home-gateways.txt):
      - OpenSSH Server runs: key-only logins from __HOSTLABEL__, allowed only from the local network
      - The RelayMCP agent runs hidden: Windows-MCP (screen control) and the RelayMCP hardware server, reachable only
        through SSH (both listen on 127.0.0.1)
    On any other network: all of it stops right away. Offline: left as-is for 10 minutes (so sleep and Wi-Fi blips
    don't churn), then stopped. Away from home nothing listens, nothing reports home, and no other network's settings
    are ever changed. A SYSTEM task switches automatically (boot, login, network changes, every 15 minutes) and
    repairs anything Windows breaks while at home.

    Generated by `relaymcp kit` on __HOSTLABEL__ for device "__DEVICENAME__". Logs: C:\ProgramData\RelayMCP\
    Remove everything:  powershell -ExecutionPolicy Bypass -File C:\ProgramData\RelayMCP\Relay-Setup.ps1 -Uninstall
#>
param([switch]$Unattended, [switch]$Uninstall)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

# ---- Filled in by `relaymcp kit` ----
$DeviceName       = '__DEVICENAME__'
$HostLabel        = '__HOSTLABEL__'
$AuthorizedKeys   = @(__PUBKEYS__)
$HomeNetworkNames = @(__NETWORKS__)
$HomeGateways     = @(__GATEWAYS__)
$ReportUrls       = @(__REPORTURLS__)
$ScreenPort       = __SCREENPORT__
$HardwarePort     = __HARDWAREPORT__
$VoicePort        = __VOICEPORT__
$WindowsMcpSpec   = '__WINDOWSMCP__'
$RelayVersion     = '__VERSION__'
# -------------------------------------
$MsiName   = 'OpenSSH-Win64-v10.0.0.0.msi'
$MsiUrl    = "https://github.com/PowerShell/Win32-OpenSSH/releases/download/10.0.0.0p2-Preview/$MsiName"
$MsiSha256 = 'ddec9c53864280759cf9f74791cefd387100e3946aa849a1c138a4ed1b96b7d9'
$KitDir    = Join-Path $env:ProgramData 'RelayMCP'
$SshDir    = Join-Path $env:ProgramData 'ssh'
$SshdExe   = Join-Path $env:ProgramFiles 'OpenSSH\sshd.exe'

$principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    $relaunch = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', ('"' + $PSCommandPath + '"'))
    if ($Unattended) { $relaunch += '-Unattended' }
    if ($Uninstall) { $relaunch += '-Uninstall' }
    Start-Process -FilePath 'powershell.exe' -Verb RunAs -ArgumentList $relaunch
    return
}

# Background controller, saved as controller.ps1 and run as SYSTEM by the RelayMCP-Controller task.
# Setup dot-sources it with -LibraryOnly to share the home-detection functions.
$Controller = @'
# RelayMCP controller: runs as SYSTEM at boot, at login, when a network connects or disconnects, and every 15 minutes.
#   At home (the router's MAC is listed in home-gateways.txt): keeps SSH and the RelayMCP agent running; repairs them.
#   On any other network: stops both right away. Offline: leaves things as they are for 10 minutes (so sleep and
#   Wi-Fi blips don't churn), then stops both. It never changes any other network's settings.
# Writes to controller.log only when it changes something.
param([switch]$LibraryOnly)
$Kit = Join-Path $env:ProgramData 'RelayMCP'
$ControllerLog = Join-Path $Kit 'controller.log'
$ScreenPort = __SCREENPORT__
$HardwarePort = __HARDWAREPORT__

function Get-HomeGateways {
    @(Get-Content (Join-Path $Kit 'home-gateways.txt') -ErrorAction SilentlyContinue |
        ForEach-Object { $_.Trim().ToUpper().Replace(':', '-') } |
        Where-Object { $_ -match '^([0-9A-F]{2}-){5}[0-9A-F]{2}$' })
}

# One entry per connected IPv4 default gateway, with the router's MAC freshly confirmed on that interface.
# A stale cache entry left over from another network is never trusted.
function Get-Gateways {
    $routes = @(Get-NetRoute -AddressFamily IPv4 -DestinationPrefix '0.0.0.0/0' -ErrorAction SilentlyContinue | Where-Object { $_.NextHop -and $_.NextHop -ne '0.0.0.0' })
    foreach ($route in $routes) {
        $ifIndex = $route.InterfaceIndex
        $gateway = $route.NextHop
        $neighbor = Get-NetNeighbor -AddressFamily IPv4 -InterfaceIndex $ifIndex -IPAddress $gateway -ErrorAction SilentlyContinue
        if (-not $neighbor -or $neighbor.State -ne 'Reachable') {
            Remove-NetNeighbor -InterfaceIndex $ifIndex -IPAddress $gateway -Confirm:$false -ErrorAction SilentlyContinue
            try { [void](New-Object System.Net.NetworkInformation.Ping).Send($gateway, 1000) } catch { }
            for ($i = 0; $i -lt 12; $i++) {
                $neighbor = Get-NetNeighbor -AddressFamily IPv4 -InterfaceIndex $ifIndex -IPAddress $gateway -ErrorAction SilentlyContinue
                if ($neighbor -and $neighbor.State -eq 'Reachable') { break }
                Start-Sleep -Milliseconds 250
            }
        }
        if ($neighbor -and $neighbor.State -eq 'Reachable') {
            $netProfile = Get-NetConnectionProfile -InterfaceIndex $ifIndex -ErrorAction SilentlyContinue | Select-Object -First 1
            [pscustomobject]@{
                InterfaceIndex = $ifIndex
                Mac            = $neighbor.LinkLayerAddress.ToUpper()
                Network        = [string]$netProfile.Name
                Category       = [string]$netProfile.NetworkCategory
            }
        }
    }
}

# Stops the RelayMCP agent (Windows-MCP, hardware server, keep-awake) and anything left over from it. Apps that the AI
# agent opened are not touched. Returns $true if anything was running.
function Stop-Agent {
    $wasRunning = [bool](Get-NetTCPConnection -LocalPort $ScreenPort, $HardwarePort -State Listen -ErrorAction SilentlyContinue)
    $task = Get-ScheduledTask -TaskName 'RelayMCP-Agent' -ErrorAction SilentlyContinue
    if ($task -and "$($task.State)" -eq 'Running') { Stop-ScheduledTask -TaskName 'RelayMCP-Agent'; $wasRunning = $true }
    $patterns = @('relaymcp\.device\.(agent|server)', ('windows_mcp serve .*--port ' + $ScreenPort))
    $procs = @(Get-CimInstance Win32_Process -Filter "Name='python.exe' OR Name='pythonw.exe'" |
        Where-Object { $cmd = ([string]$_.CommandLine) -replace '\s+', ' '; @($patterns | Where-Object { $cmd -match $_ }).Count })
    foreach ($p in $procs) { Stop-Process -Id $p.ProcessId -Force -ErrorAction SilentlyContinue; $wasRunning = $true }
    return $wasRunning
}

if ($LibraryOnly) { return }

$mode = 'unknown'
$changes = New-Object System.Collections.Generic.List[string]
try {
    if ((Test-Path $ControllerLog) -and (Get-Item $ControllerLog).Length -gt 256KB) {
        Set-Content -Path $ControllerLog -Value (Get-Content $ControllerLog -Tail 200)
    }
    $stateFile = Join-Path $Kit 'state.txt'
    $offlineFile = Join-Path $Kit 'offline-since.txt'
    $previous = [string](Get-Content $stateFile -ErrorAction SilentlyContinue | Select-Object -First 1)
    $homeMacs = @(Get-HomeGateways)
    $gateways = @(Get-Gateways)
    $homeNets = @($gateways | Where-Object { $homeMacs -contains $_.Mac })
    $reason = ''
    if ($homeNets.Count) {
        $mode = 'home'
        $reason = "on home network '$($homeNets[0].Network)'"
    } elseif ($gateways.Count) {
        # On some other network: switch off right away.
        $mode = 'away'
        $reason = "on another network ('$($gateways[0].Network)')"
    } else {
        # No network at all (asleep, Wi-Fi blip, airplane mode): nothing can reach the handheld, so don't churn.
        # Stay as-is for 10 minutes, then switch off.
        $since = $null
        try { $since = [datetime](Get-Content $offlineFile -ErrorAction Stop | Select-Object -First 1) } catch { }
        if (-not $since) { $since = Get-Date; Set-Content -Path $offlineFile -Value $since.ToString('o') -Encoding ascii }
        $mode = if ($previous -eq 'home' -and ((Get-Date) - $since).TotalMinutes -lt 10) { 'home' } else { 'away' }
        $reason = 'offline for 10+ minutes'
    }
    if ($gateways.Count) { Remove-Item -Path $offlineFile -Force -ErrorAction SilentlyContinue }
    if ($mode -ne $previous) {
        Set-Content -Path $stateFile -Value $mode -Encoding ascii
        $changes.Add($reason)
    }

    # SSH firewall rules: Private networks and the local subnet only (defense in depth; affects nothing else).
    if (-not (Get-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -ErrorAction SilentlyContinue)) {
        New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH SSH Server (sshd)' -Direction Inbound -Protocol TCP -LocalPort 22 -Action Allow -Profile Private -RemoteAddress LocalSubnet | Out-Null
        $changes.Add('re-created the SSH firewall rule')
    }
    foreach ($rule in @(Get-NetFirewallRule -Direction Inbound | Where-Object { $_.Name -like '*OpenSSH*' -or $_.DisplayName -like '*sshd*' })) {
        $scope = ($rule | Get-NetFirewallAddressFilter).RemoteAddress
        if ("$($rule.Enabled)" -ne 'True' -or "$($rule.Profile)" -ne 'Private' -or "$scope" -ne 'LocalSubnet') {
            $rule | Set-NetFirewallRule -Enabled True -Profile Private -RemoteAddress LocalSubnet
            $changes.Add("re-scoped firewall rule '$($rule.DisplayName)'")
        }
    }

    # sshd stays registered on Manual start; this task decides when it runs.
    $exe = Join-Path $env:ProgramFiles 'OpenSSH\sshd.exe'
    $svc = Get-CimInstance Win32_Service -Filter "Name='sshd'"
    if (-not $svc -and (Test-Path $exe)) {
        New-Service -Name sshd -DisplayName 'OpenSSH SSH Server' -BinaryPathName ('"' + $exe + '"') -StartupType Manual | Out-Null
        $changes.Add('re-registered the missing sshd service')
    } elseif ($svc -and -not (Test-Path $svc.PathName.Trim('"')) -and (Test-Path $exe)) {
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\sshd' -Name ImagePath -Value ('"' + $exe + '"')
        $changes.Add("repointed sshd to $exe")
    }
    $sshd = Get-Service -Name sshd -ErrorAction SilentlyContinue
    if ($sshd -and "$($sshd.StartType)" -ne 'Manual') {
        Set-Service -Name sshd -StartupType Manual
        $changes.Add("sshd start type $($sshd.StartType) -> Manual")
    }

    if ($mode -eq 'home') {
        foreach ($net in $homeNets) {
            if ($net.Category -eq 'Public') {
                Set-NetConnectionProfile -InterfaceIndex $net.InterfaceIndex -NetworkCategory Private
                $changes.Add("home network '$($net.Network)' was Public; set to Private")
            }
        }
        if ($sshd -and "$($sshd.Status)" -ne 'Running') { Start-Service -Name sshd; $changes.Add('started SSH') }
        if ((Get-CimInstance Win32_ComputerSystem).UserName) {
            # The agent restarts its own servers if they exit; this only (re)starts the agent itself.
            $agentTask = Get-ScheduledTask -TaskName 'RelayMCP-Agent' -ErrorAction SilentlyContinue
            if ($agentTask -and "$($agentTask.State)" -ne 'Running') {
                Start-ScheduledTask -TaskName 'RelayMCP-Agent'
                $changes.Add('started the RelayMCP agent (Windows-MCP, hardware server, keep-awake)')
            }
        }
    } else {
        if ($sshd -and "$($sshd.Status)" -ne 'Stopped') { Stop-Service -Name sshd -Force; $changes.Add('stopped SSH') }
        if (Stop-Agent) { $changes.Add('stopped the RelayMCP agent') }
    }
} catch {
    $changes.Add("error: $($_.Exception.Message)")
}
if ($changes.Count) { "$(Get-Date -Format s) [$mode] $($changes -join '; ')" | Add-Content -Path $ControllerLog }
'@

function Step([string]$Message) { Write-Host "==> $Message" -ForegroundColor Cyan }
function Info([string]$Message) { Write-Host "    $Message" }

function Invoke-Icacls([string[]]$Arguments) {
    & icacls.exe @Arguments | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "icacls $($Arguments -join ' ') failed ($LASTEXITCODE)" }
}

function Restart-SshdSafely {
    # A one-off SYSTEM task restarts sshd, so an SSH session running this script can't cut the restart short.
    $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument '-NoProfile -WindowStyle Hidden -Command "Start-Sleep -Seconds 2; Restart-Service sshd"'
    Register-ScheduledTask -TaskName 'RelayMCP-RestartSshd' -Action $action -User 'SYSTEM' -RunLevel Highest -Force | Out-Null
    Start-ScheduledTask -TaskName 'RelayMCP-RestartSshd'
}

function Show-Result([string]$Text, [bool]$Ok) {
    if ($Unattended) { return }
    Add-Type -AssemblyName System.Windows.Forms
    $owner = New-Object System.Windows.Forms.Form -Property @{ TopMost = $true }
    $icon = if ($Ok) { [System.Windows.Forms.MessageBoxIcon]::Information } else { [System.Windows.Forms.MessageBoxIcon]::Error }
    [System.Windows.Forms.MessageBox]::Show($owner, $Text, 'RelayMCP', [System.Windows.Forms.MessageBoxButtons]::OK, $icon) | Out-Null
}

function Read-YesNo([string]$Text) {
    if ($Unattended) { return $false }
    Add-Type -AssemblyName System.Windows.Forms
    $owner = New-Object System.Windows.Forms.Form -Property @{ TopMost = $true }
    $answer = [System.Windows.Forms.MessageBox]::Show($owner, $Text, 'RelayMCP', [System.Windows.Forms.MessageBoxButtons]::YesNo, [System.Windows.Forms.MessageBoxIcon]::Question)
    return ($answer -eq [System.Windows.Forms.DialogResult]::Yes)
}

# Only ever called while on the home network, so status never goes to a device on some other network.
function Send-Report([System.Collections.IDictionary]$Fields) {
    $query = ($Fields.GetEnumerator() | ForEach-Object { '{0}={1}' -f $_.Key, [uri]::EscapeDataString([string]$_.Value) }) -join '&'
    foreach ($url in $ReportUrls) {
        try { Invoke-RestMethod -Uri ('{0}?{1}' -f $url, $query) -TimeoutSec 4 | Out-Null; return } catch { }
    }
}

# Removes RelayMCP from this handheld. OpenSSH Server and the ViGEmBus driver stay installed (remove them in
# Settings > Apps if you like); SSH is stopped and disabled, and this computer's key is removed.
function Invoke-Uninstall {
    Step 'Removing RelayMCP'
    $libFile = Join-Path $KitDir 'controller.ps1'
    if (Test-Path $libFile) { . $libFile -LibraryOnly; [void](Stop-Agent) }
    foreach ($t in @(Get-ScheduledTask -ErrorAction SilentlyContinue | Where-Object { $_.TaskName -like 'RelayMCP-*' })) {
        if ("$($t.State)" -eq 'Running') { Stop-ScheduledTask -TaskName $t.TaskName -ErrorAction SilentlyContinue }
        Unregister-ScheduledTask -TaskName $t.TaskName -Confirm:$false
        Info "removed task $($t.TaskName)"
    }
    foreach ($lnk in @((Join-Path ([Environment]::GetFolderPath('Desktop')) 'Repair RelayMCP.lnk'),
                       (Join-Path ([Environment]::GetFolderPath('CommonPrograms')) 'Repair RelayMCP.lnk'),
                       (Join-Path ([Environment]::GetFolderPath('Desktop')) 'Ask Copilot.lnk'),
                       (Join-Path ([Environment]::GetFolderPath('Programs')) 'Ask Copilot.lnk'))) {
        Remove-Item -Path $lnk -Force -ErrorAction SilentlyContinue
    }
    $env:Path = "$(Join-Path $env:USERPROFILE '.local\bin');$env:Path"
    if (Get-Command uv -ErrorAction SilentlyContinue) {
        foreach ($tool in @('relaymcp-device', 'windows-mcp')) { cmd /c "uv tool uninstall $tool 2>&1" | Out-Null }
        Info 'uninstalled the RelayMCP device runtime and Windows-MCP'
    }
    Remove-Item -Recurse -Force -Path (Join-Path $env:LOCALAPPDATA 'RelayMCP') -ErrorAction SilentlyContinue
    $keysFile = Join-Path $SshDir 'administrators_authorized_keys'
    if (Test-Path $keysFile) {
        $keep = @(Get-Content $keysFile | Where-Object { $_.Trim() -and ($AuthorizedKeys -notcontains $_) })
        if ($keep.Count) { Set-Content -Path $keysFile -Value $keep -Encoding ascii } else { Remove-Item $keysFile -Force }
        Info "removed $HostLabel's SSH key"
    }
    Set-Location $env:SystemRoot
    Remove-Item -Recurse -Force -Path $KitDir -ErrorAction SilentlyContinue
    $msg = "RelayMCP was removed from this handheld.`n`nOpenSSH Server and the Nefarius ViGEmBus driver are still installed " +
        "(SSH is stopped and disabled); remove them in Settings > Apps if you like."
    Write-Host $msg -ForegroundColor Green
    Show-Result $msg $true
    # Last, because it ends an SSH session that may be running this very uninstall.
    Remove-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -ErrorAction SilentlyContinue
    if (Get-Service -Name sshd -ErrorAction SilentlyContinue) {
        Set-Service -Name sshd -StartupType Disabled
        Stop-Service -Name sshd -Force -ErrorAction SilentlyContinue
    }
}

if ($Uninstall) {
    try { Invoke-Uninstall } catch { Write-Host "Uninstall failed: $($_.Exception.Message)" -ForegroundColor Red; Show-Result "Uninstall hit a problem:`n`n$($_.Exception.Message)" $false }
    return
}

$setupLog = Join-Path $KitDir 'setup.log'
$transcribing = $false
$atHome = $false
$voiceShortcut = $false
$results = New-Object System.Collections.Generic.List[string]
try {
    Step 'Preparing C:\ProgramData\RelayMCP'
    New-Item -ItemType Directory -Force -Path $KitDir | Out-Null
    Invoke-Icacls @($KitDir, '/inheritance:r', '/grant', '*S-1-5-32-544:(OI)(CI)F', '/grant', '*S-1-5-18:(OI)(CI)F', '/grant', '*S-1-5-32-545:(OI)(CI)RX', '/Q')
    if ($PSScriptRoot -and ($PSScriptRoot.TrimEnd('\') -ne $KitDir)) {
        Copy-Item -Path $PSCommandPath -Destination (Join-Path $KitDir 'Relay-Setup.ps1') -Force
        foreach ($f in @($MsiName, 'relaymcp-device.zip', 'ViGEmBusSetup_x64.msi')) {
            $src = Join-Path $PSScriptRoot $f
            if (Test-Path $src) { Copy-Item -Path $src -Destination (Join-Path $KitDir $f) -Force }
        }
    }
    $controllerFile = Join-Path $KitDir 'controller.ps1'
    Set-Content -Path $controllerFile -Value $Controller -Encoding ascii
    # Read by the device runtime: its name on the controlling computer, how to refer to that computer, and ports.
    # Keys added by hand (e.g. "vocabulary") are kept.
    $deviceFile = Join-Path $KitDir 'device.json'
    $deviceJson = [ordered]@{}
    try { (Get-Content $deviceFile -Raw -ErrorAction Stop | ConvertFrom-Json).PSObject.Properties | ForEach-Object { $deviceJson[$_.Name] = $_.Value } } catch { }
    $deviceJson['name'] = $DeviceName
    $deviceJson['host_label'] = $HostLabel
    $deviceJson['version'] = $RelayVersion
    $deviceJson['ports'] = [ordered]@{ screen = $ScreenPort; hardware = $HardwarePort; voice = $VoicePort }
    Set-Content -Path $deviceFile -Value ($deviceJson | ConvertTo-Json) -Encoding utf8
    Invoke-Icacls @((Join-Path $KitDir '*'), '/reset', '/T', '/Q')
    if ((Test-Path $setupLog) -and (Get-Item $setupLog).Length -gt 1MB) { Remove-Item $setupLog -Force }
    Start-Transcript -Path $setupLog -Append | Out-Null
    $transcribing = $true
    . $controllerFile -LibraryOnly

    Step 'Home network'
    $gatewayFile = Join-Path $KitDir 'home-gateways.txt'
    $knownGateways = @(@(Get-HomeGateways) + @($HomeGateways | ForEach-Object { $_.Trim().ToUpper().Replace(':', '-') }) | Where-Object { $_ } | Sort-Object -Unique)
    Set-Content -Path $gatewayFile -Value $knownGateways -Encoding ascii
    Set-Content -Path (Join-Path $KitDir 'home-networks.txt') -Value $HomeNetworkNames -Encoding ascii
    Remove-Item -Path (Join-Path $KitDir 'trusted-networks.txt') -Force -ErrorAction SilentlyContinue
    $gateways = @(Get-Gateways)
    $homeNets = @($gateways | Where-Object { $knownGateways -contains $_.Mac })
    if (-not $homeNets.Count) {
        # Same Wi-Fi name but an unknown router: probably a new router at home. Only a person can confirm that.
        $lookalike = @($gateways | Where-Object {
            $name = $_.Network
            @($HomeNetworkNames | Where-Object { $name -eq $_ -or $name -match ('^' + [regex]::Escape($_) + ' \d+$') }).Count -gt 0
        }) | Select-Object -First 1
        if ($lookalike) {
            $question = "You're connected to '$($lookalike.Network)', but its router isn't the one RelayMCP knows as your home router.`n`n" +
                "If you got a new router, choose Yes to trust this network as home.`nIf you're anywhere else, choose No."
            if (Read-YesNo $question) {
                $knownGateways = @(@($knownGateways) + $lookalike.Mac | Sort-Object -Unique)
                Set-Content -Path $gatewayFile -Value $knownGateways -Encoding ascii
                $homeNets = @($lookalike)
                Info "trusted router $($lookalike.Mac) as home"
            } else {
                Info "'$($lookalike.Network)' ($($lookalike.Mac)) is not a known home router; not trusting it"
            }
        }
    }
    $atHome = $homeNets.Count -gt 0
    Info $(if ($atHome) { "at home ('$($homeNets[0].Network)')" } else { 'not on the home network: remote access will stay off here' })

    Step 'OpenSSH Server'
    if (-not (Get-Service -Name sshd -ErrorAction SilentlyContinue)) {
        if (-not (Test-Path $SshdExe)) {
            $msi = Join-Path $KitDir $MsiName
            if (-not ((Test-Path $msi) -and ((Get-FileHash -Path $msi -Algorithm SHA256).Hash -eq $MsiSha256))) {
                Info 'downloading the OpenSSH installer...'
                Invoke-WebRequest -UseBasicParsing -Uri $MsiUrl -OutFile $msi
            }
            if ((Get-FileHash -Path $msi -Algorithm SHA256).Hash -ne $MsiSha256) { throw 'The OpenSSH installer failed its SHA256 check.' }
            Info 'installing OpenSSH (about 30 seconds)...'
            $install = Start-Process -FilePath msiexec.exe -ArgumentList "/i `"$msi`" ADDLOCAL=Server /qn /norestart" -Wait -PassThru
            if ($install.ExitCode -notin 0, 3010) { throw "The OpenSSH installer failed (exit code $($install.ExitCode))." }
        }
        if (-not (Get-Service -Name sshd -ErrorAction SilentlyContinue)) {
            New-Service -Name sshd -DisplayName 'OpenSSH SSH Server' -BinaryPathName ('"' + $SshdExe + '"') -StartupType Manual | Out-Null
        }
    }
    $svc = Get-CimInstance Win32_Service -Filter "Name='sshd'"
    if (-not (Test-Path $svc.PathName.Trim('"')) -and (Test-Path $SshdExe)) {
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\sshd' -Name ImagePath -Value ('"' + $SshdExe + '"')
        $svc = Get-CimInstance Win32_Service -Filter "Name='sshd'"
    }
    $sshdPath = $svc.PathName.Trim('"')
    Set-Service -Name sshd -StartupType Manual

    Step 'Firewall (SSH from the home network only)'
    if (-not (Get-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -ErrorAction SilentlyContinue)) {
        New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH SSH Server (sshd)' -Direction Inbound -Protocol TCP -LocalPort 22 -Action Allow -Profile Private -RemoteAddress LocalSubnet | Out-Null
    }
    Get-NetFirewallRule -Direction Inbound | Where-Object { $_.Name -like '*OpenSSH*' -or $_.DisplayName -like '*sshd*' } | Set-NetFirewallRule -Enabled True -Profile Private -RemoteAddress LocalSubnet

    Step "SSH key from $HostLabel, and hardening"
    $cfg = Join-Path $SshDir 'sshd_config'
    if (-not (Test-Path $cfg)) {
        # First run: sshd writes its default config and host keys the first time it starts.
        Info 'initializing SSH (first run)'
        Start-Service -Name sshd
        for ($i = 0; ($i -lt 30) -and -not (Test-Path $cfg); $i++) { Start-Sleep -Milliseconds 500 }
        if (-not $atHome) { Stop-Service -Name sshd -Force }
    }
    if (-not (Test-Path $cfg)) { throw 'sshd did not create its config file.' }
    $keysFile = Join-Path $SshDir 'administrators_authorized_keys'
    $keys = @()
    if (Test-Path $keysFile) { $keys = @(Get-Content $keysFile | Where-Object { $_.Trim() }) }
    $missing = @($AuthorizedKeys | Where-Object { $keys -notcontains $_ })
    if ($missing.Count) {
        Set-Content -Path $keysFile -Value ($keys + $missing) -Encoding ascii
        Info "authorized $($missing.Count) new key(s)"
    }
    Invoke-Icacls @($keysFile, '/inheritance:r', '/grant', '*S-1-5-32-544:F', '/grant', '*S-1-5-18:F', '/Q')
    $orig = @(Get-Content $cfg)
    $new = @($orig -replace '^\s*#?\s*PasswordAuthentication\s+\w+\s*$', 'PasswordAuthentication no' -replace '^\s*#?\s*KbdInteractiveAuthentication\s+\w+\s*$', 'KbdInteractiveAuthentication no')
    # SFTP (scp uses it): Windows OpenSSH launches the subsystem by name through a shell, and a server-only install
    # isn't on PATH, so point at sftp-server.exe by its absolute 8.3 path (no spaces).
    $sftpExe = Join-Path (Split-Path $sshdPath) 'sftp-server.exe'
    if (Test-Path $sftpExe) {
        $sftpShort = (New-Object -ComObject Scripting.FileSystemObject).GetFile($sftpExe).ShortPath
        if ($sftpShort -notmatch ' ') {
            $new = @($new -replace '^\s*Subsystem\s+sftp\s+.*$', "Subsystem sftp $sftpShort")
            if (-not ($new -match '^Subsystem\s+sftp\s')) { $new = @("Subsystem sftp $sftpShort") + $new }
        } else {
            $sftpDir = Split-Path $sftpExe
            $machinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
            if (($machinePath -split ';') -notcontains $sftpDir) {
                [Environment]::SetEnvironmentVariable('Path', "$machinePath;$sftpDir", 'Machine')
                Info 'added OpenSSH to PATH for SFTP (takes effect after a restart)'
            }
        }
    }
    if (-not ($new -match '^PasswordAuthentication no$')) { $new = @('PasswordAuthentication no') + $new }
    if (-not ($new -match '^KbdInteractiveAuthentication no$')) { $new = @('KbdInteractiveAuthentication no') + $new }
    # Drop dead sessions within about a minute, so a Wi-Fi blip can't leave a stale session holding the voice
    # tunnel's port (127.0.0.1:$VoicePort) and block the reconnect.
    $new = @($new | Where-Object { $_ -notmatch '^\s*#?\s*ClientAlive(Interval|CountMax)\s' })
    $new = @('ClientAliveInterval 15', 'ClientAliveCountMax 4') + $new
    if (($orig -join "`n") -ne ($new -join "`n")) {
        Copy-Item -Path $cfg -Destination "$cfg.bak-relaymcp" -Force
        Set-Content -Path $cfg -Value $new -Encoding ascii
        & $sshdPath -t
        if ($LASTEXITCODE -ne 0) {
            Copy-Item -Path "$cfg.bak-relaymcp" -Destination $cfg -Force
            throw 'sshd_config failed validation; restored the backup.'
        }
        Info 'sshd_config updated (key-only logins, SFTP path, dead-session timeout)'
        if ((Get-Service -Name sshd).Status -eq 'Running') { Restart-SshdSafely }
    }
    if (-not (Test-Path 'HKLM:\SOFTWARE\OpenSSH')) { New-Item -Path 'HKLM:\SOFTWARE\OpenSSH' | Out-Null }
    New-ItemProperty -Path 'HKLM:\SOFTWARE\OpenSSH' -Name DefaultShell -PropertyType String -Force -Value "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" | Out-Null

    Step 'Windows-MCP (screen control, runs hidden)'
    $bin = Join-Path $env:USERPROFILE '.local\bin'
    $env:Path = "$bin;$env:Path"
    if (-not (Test-Path (Join-Path $bin 'uv.exe'))) {
        Info 'installing uv...'
        Invoke-RestMethod -Uri 'https://astral.sh/uv/install.ps1' | Invoke-Expression | Out-Null
    }
    $toolList = [string](cmd /c 'uv tool list 2>nul')
    $wmVersion = ($WindowsMcpSpec -split '==')[1]
    if (-not ($toolList -match 'windows-mcp v') -or ($wmVersion -and -not ($toolList -match ('windows-mcp v' + [regex]::Escape($wmVersion) + '\b')))) {
        Info "installing Windows-MCP ($WindowsMcpSpec; the first run downloads Python, 1-2 minutes)..."
        [void](Stop-Agent)
        $out = cmd /c "uv tool install --force $WindowsMcpSpec 2>&1"
        if ($LASTEXITCODE -ne 0) { throw "Installing Windows-MCP failed: $(($out | Select-Object -Last 2) -join ' ')" }
    }
    $toolDir = [string](cmd /c 'uv tool dir 2>nul' | Select-Object -First 1)
    $mcpPython = Join-Path $toolDir.Trim() 'windows-mcp\Scripts\python.exe'
    if (-not (Test-Path $mcpPython)) { throw "Windows-MCP's Python wasn't found at $mcpPython." }

    Step 'Virtual gamepad driver (ViGEmBus)'
    # Must come before the runtime: building vgamepad (the driver's Python wrapper) on a machine without the driver
    # opens the driver's interactive installer and waits for clicks. Installed silently here instead, from the kit's
    # copy, after checking the publisher's signature.
    $vigemRegistered = [bool](Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall' -ErrorAction SilentlyContinue |
        Get-ItemProperty -ErrorAction SilentlyContinue | Where-Object { $_.DisplayName -like 'Nefarius Virtual Gamepad Emulation Bus Driver*' })
    $vigemPresent = [bool](Get-PnpDevice -FriendlyName '*Virtual Gamepad Emulation Bus*' -PresentOnly -ErrorAction SilentlyContinue)
    if ($vigemRegistered -and $vigemPresent) {
        Info 'already installed'
    } else {
        $vigem = Join-Path $KitDir 'ViGEmBusSetup_x64.msi'
        if (-not (Test-Path $vigem)) { throw 'ViGEmBusSetup_x64.msi is missing from this kit. Rebuild it with `relaymcp kit`.' }
        $sig = Get-AuthenticodeSignature -FilePath $vigem
        if ($sig.Status -ne 'Valid' -or $sig.SignerCertificate.Subject -notmatch 'Nefarius') { throw "The ViGEmBus installer's signature isn't valid ($($sig.Status))." }
        Info 'installing the virtual gamepad driver (about 20 seconds)...'
        $p = Start-Process msiexec.exe -ArgumentList "/i `"$vigem`" /qn /norestart /l*v `"$(Join-Path $KitDir 'vigembus-install.log')`"" -Wait -PassThru
        if ($p.ExitCode -notin 0, 3010) { throw "The ViGEmBus installer failed (exit code $($p.ExitCode)); see vigembus-install.log." }
    }

    Step 'RelayMCP device runtime (hardware tools, voice; runs hidden)'
    $hhZip = Join-Path $KitDir 'relaymcp-device.zip'
    $hhDir = Join-Path $KitDir 'device'
    $hhVenv = Join-Path $toolDir.Trim() 'relaymcp-device'
    $hhExe = Join-Path $hhVenv 'Scripts\relaymcp-device.exe'
    $hhInstalled = $false
    if (Test-Path $hhZip) {
        $hhHash = (Get-FileHash -Path $hhZip -Algorithm SHA256).Hash
        $hashFile = Join-Path $KitDir 'relaymcp-device.sha256'
        $current = [string](Get-Content $hashFile -ErrorAction SilentlyContinue | Select-Object -First 1)
        if ($current -ne $hhHash -or -not (Test-Path $hhExe)) {
            Info 'installing the device runtime (the first time downloads Python 3.12 and speech libraries)...'
            [void](Stop-Agent)
            Remove-Item -Recurse -Force $hhDir -ErrorAction SilentlyContinue
            Expand-Archive -Path $hhZip -DestinationPath $hhDir -Force
            $out = cmd /c "uv tool install --force --reinstall-package relaymcp-device --python 3.12 `"$hhDir`" 2>&1"
            if ($LASTEXITCODE -ne 0) { throw "Installing the device runtime failed: $(($out | Select-Object -Last 3) -join ' ')" }
            Set-Content -Path $hashFile -Value $hhHash -Encoding ascii
        }
        $hhInstalled = Test-Path $hhExe
        if ($hhInstalled) {
            # Natural voice for spoken replies (~200 MB, first time only; hash-checked). Optional: without it the
            # Windows voice is used.
            $hhPython = Join-Path $hhVenv 'Scripts\python.exe'
            $voiceOut = cmd /c "`"$hhPython`" -m relaymcp.device.tts --download 2>&1"
            if ($LASTEXITCODE -ne 0) { Info "natural voice not downloaded yet (using the Windows voice): $(($voiceOut | Select-Object -Last 1))" }
            elseif ("$voiceOut" -match 'downloading') { Info 'downloaded the natural voice' }
        }
    } else {
        throw 'relaymcp-device.zip is missing from this kit. Rebuild it with `relaymcp kit`.'
    }
    if ($hhInstalled) {
        # Fixed-action SYSTEM task that closes Armoury Crate's "External controller connected" notice (an elevated
        # window the non-elevated server can't click) without choosing anything. Standard users may run only this task.
        $service = New-Object -ComObject Schedule.Service
        $service.Connect()
        $def = $service.NewTask(0)
        $def.RegistrationInfo.Description = "Closes Armoury Crate's external-controller notice raised by RelayMCP's virtual gamepad. Fixed action; see C:\ProgramData\RelayMCP."
        $def.Settings.DisallowStartIfOnBatteries = $false
        $def.Settings.StopIfGoingOnBatteries = $false
        $def.Settings.ExecutionTimeLimit = 'PT1M'
        $def.Settings.MultipleInstances = 2
        $def.Principal.UserId = 'SYSTEM'
        $def.Principal.LogonType = 5
        $def.Principal.RunLevel = 1
        $a = $def.Actions.Create(0)
        $a.Path = "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe"
        $a.Arguments = '-NoProfile -NonInteractive -WindowStyle Hidden -Command "Get-Process -Name ExternalControllerHelper -ErrorAction SilentlyContinue | Stop-Process -Force; exit 0"'
        [void]$service.GetFolder('\').RegisterTaskDefinition('RelayMCP-DismissControllerNotice', $def, 6, 'SYSTEM', $null, 5, 'D:(A;;FA;;;SY)(A;;FA;;;BA)(A;;GRGX;;;AU)')
    }

    Step 'RelayMCP agent (runs Windows-MCP and the hardware server hidden; keeps the handheld awake while in use)'
    # pythonw.exe: no window and no console. The agent starts each server with a hidden console, restarts them if they
    # exit, and ends them when it stops. RelayMCP-Controller starts it only at home and stops it everywhere else.
    $agentPython = Join-Path $hhVenv 'Scripts\pythonw.exe'
    if (-not $hhInstalled -or -not (Test-Path $agentPython)) { throw "The device runtime didn't install, so the RelayMCP agent can't run." }
    $agentAction = New-ScheduledTaskAction -Execute $agentPython -Argument '-m relaymcp.device.agent' -WorkingDirectory $env:LOCALAPPDATA
    $agentPrincipal = New-ScheduledTaskPrincipal -UserId ([Security.Principal.WindowsIdentity]::GetCurrent().Name) -LogonType Interactive -RunLevel Limited
    $agentSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -MultipleInstances IgnoreNew -ExecutionTimeLimit ([TimeSpan]::Zero) -Priority 5
    Register-ScheduledTask -TaskName 'RelayMCP-Agent' -Description 'RelayMCP: runs Windows-MCP (screen control) and the hardware server hidden, and keeps the handheld awake while an AI agent uses it. No triggers: RelayMCP-Controller starts it only while at home. See C:\ProgramData\RelayMCP.' -Action $agentAction -Principal $agentPrincipal -Settings $agentSettings -Force | Out-Null
    [void](Stop-Agent)  # the controller starts it again with the current version

    Step 'Controller task (remote access on at home, off everywhere else)'
    $taskAction = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument ('-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "' + $controllerFile + '"')
    $atBoot = New-ScheduledTaskTrigger -AtStartup
    $atBoot.Delay = 'PT30S'
    $atLogon = New-ScheduledTaskTrigger -AtLogOn
    $atLogon.Delay = 'PT20S'
    $every15 = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) -RepetitionInterval (New-TimeSpan -Minutes 15)
    $eventClass = Get-CimClass -Namespace 'Root/Microsoft/Windows/TaskScheduler' -ClassName 'MSFT_TaskEventTrigger'
    $onNetwork = New-CimInstance -CimClass $eventClass -ClientOnly
    $onNetwork.Enabled = $true
    $onNetwork.Delay = 'PT10S'
    $onNetwork.Subscription = '<QueryList><Query Id="0" Path="Microsoft-Windows-NetworkProfile/Operational"><Select Path="Microsoft-Windows-NetworkProfile/Operational">*[System[(EventID=10000 or EventID=10001)]]</Select></Query></QueryList>'
    $taskSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Minutes 5) -Priority 7
    Register-ScheduledTask -TaskName 'RelayMCP-Controller' -Description 'RelayMCP: turns remote access (SSH + the RelayMCP agent) on at home and off everywhere else; repairs it at home. See C:\ProgramData\RelayMCP.' -Action $taskAction -Trigger @($atBoot, $atLogon, $every15, $onNetwork) -Settings $taskSettings -User 'SYSTEM' -RunLevel Highest -Force | Out-Null

    Step 'Repair shortcut (Desktop and Start > All apps)'
    $shell = New-Object -ComObject WScript.Shell
    $psExe = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
    $lnkArgs = '-NoProfile -ExecutionPolicy Bypass -File "' + (Join-Path $KitDir 'Relay-Setup.ps1') + '"'
    foreach ($folder in @([Environment]::GetFolderPath('Desktop'), [Environment]::GetFolderPath('CommonPrograms'))) {
        if (-not $folder) { continue }
        $lnkPath = Join-Path $folder 'Repair RelayMCP.lnk'
        $lnk = $shell.CreateShortcut($lnkPath)
        $lnk.TargetPath = $psExe
        $lnk.Arguments = $lnkArgs
        $lnk.WorkingDirectory = $KitDir
        $lnk.IconLocation = "$env:SystemRoot\System32\imageres.dll,73"
        $lnk.Description = "Re-enable remote control from $HostLabel (RelayMCP; works at home only)"
        $lnk.Save()
        $bytes = [System.IO.File]::ReadAllBytes($lnkPath)
        $bytes[0x15] = $bytes[0x15] -bor 0x20
        [System.IO.File]::WriteAllBytes($lnkPath, $bytes)
    }

    $askExe = Join-Path $hhVenv 'Scripts\relaymcp-ask.exe'
    if ($hhInstalled -and (Test-Path $askExe)) {
        Step "'Ask Copilot' voice shortcut (Desktop and Start > All apps)"
        $askIcon = Join-Path $hhVenv 'Lib\site-packages\relaymcp\device\assets\ask-copilot.ico'
        foreach ($folder in @([Environment]::GetFolderPath('Desktop'), [Environment]::GetFolderPath('Programs'))) {
            if (-not $folder) { continue }
            $lnk = $shell.CreateShortcut((Join-Path $folder 'Ask Copilot.lnk'))
            $lnk.TargetPath = $askExe
            $lnk.WorkingDirectory = Split-Path $askExe
            if (Test-Path $askIcon) { $lnk.IconLocation = "$askIcon,0" }
            $lnk.Description = 'Talk to your AI agent: tap, then speak (or hold View + Menu on the controller)'
            $lnk.Save()
        }
        $voiceShortcut = $true
    }

    Step 'Applying home/away state'
    $lastRun = (Get-ScheduledTaskInfo -TaskName 'RelayMCP-Controller').LastRunTime
    Start-ScheduledTask -TaskName 'RelayMCP-Controller'
    for ($i = 0; $i -lt 120; $i++) {
        Start-Sleep -Milliseconds 500
        if (((Get-ScheduledTaskInfo -TaskName 'RelayMCP-Controller').LastRunTime -ne $lastRun) -and ((Get-ScheduledTask -TaskName 'RelayMCP-Controller').State -ne 'Running')) { break }
    }
    $mode = [string](Get-Content (Join-Path $KitDir 'state.txt') -ErrorAction SilentlyContinue | Select-Object -First 1)
    $atHome = ($mode -eq 'home') -and ($homeNets.Count -gt 0)
    $listening = { [bool](Get-NetTCPConnection -LocalPort $ScreenPort -State Listen -ErrorAction SilentlyContinue) }
    if ($atHome) {
        for ($i = 0; ($i -lt 40) -and -not (& $listening); $i++) { Start-Sleep -Milliseconds 500 }
        $hhUp = { [bool](Get-NetTCPConnection -LocalPort $HardwarePort -State Listen -ErrorAction SilentlyContinue) }
        for ($i = 0; $hhInstalled -and ($i -lt 60) -and -not (& $hhUp); $i++) { Start-Sleep -Milliseconds 500 }
        $results.Add("At home ('$($homeNets[0].Network)'): remote access is ON")
        $results.Add("SSH: $((Get-Service sshd).Status), key-only, local network only")
        $results.Add('Screen control: ' + $(if (& $listening) { 'running (hidden)' } else { 'starting' }))
        if ($hhInstalled) { $results.Add('Hardware tools: ' + $(if (& $hhUp) { 'running (hidden)' } else { 'starting' })) }
        $results.Add('Keep-awake: only while an AI agent is using the handheld')
        if ($voiceShortcut) { $results.Add("Voice prompts: hold View + Menu, or tap 'Ask Copilot'") }
    } elseif (-not $gateways.Count) {
        $results.Add('No network right now. Remote access switches off after 10 minutes offline')
        $results.Add("and back on by itself when you're home on $($HomeNetworkNames -join ' / ').")
    } else {
        $results.Add('Away from home: remote access is OFF (SSH, screen control and hardware tools stopped)')
        $results.Add("It turns back on by itself when you're home on $($HomeNetworkNames -join ' / ').")
    }
    $results.Add("Repair shortcut: 'Repair RelayMCP' on the Desktop and in Start > All apps")

    if ($atHome) {
        $hostKey = ((Get-Content (Join-Path $SshDir 'ssh_host_ed25519_key.pub') -TotalCount 1) -split ' ')[0..1] -join ' '
        $ip = (Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex $homeNets[0].InterfaceIndex -ErrorAction SilentlyContinue | Where-Object { $_.IPAddress -notlike '169.254.*' } | Select-Object -First 1).IPAddress
        Send-Report ([ordered]@{ status = 'ok'; name = $DeviceName; version = $RelayVersion; user = $env:USERNAME; host = $env:COMPUTERNAME; ip = $ip; hostkey = $hostKey; mcp = (& $listening); gateway = (($homeNets | ForEach-Object { $_.Mac }) -join ',') })
        $summary = "All set! Your AI agent on $HostLabel can reach this handheld while it's at home.`n`n" + ($results -join "`n")
    } else {
        $summary = "All set. You're not on your home network right now, so remote access is off or switching off.`n`n" + ($results -join "`n")
    }
    Write-Host ''
    Write-Host $summary -ForegroundColor Green
    Show-Result $summary $true
} catch {
    $message = $_.Exception.Message
    Write-Host "Setup failed: $message" -ForegroundColor Red
    if ($atHome) { Send-Report ([ordered]@{ status = 'error'; name = $DeviceName; user = $env:USERNAME; host = $env:COMPUTERNAME; error = $message }) }
    Show-Result "Setup hit a problem:`n`n$message`n`nLog: $setupLog" $false
    if ($Unattended) { $global:LASTEXITCODE = 1 }
} finally {
    if ($transcribing) { try { Stop-Transcript | Out-Null } catch { } }
}
