"""Builds the setup kit for the handheld: Relay-Setup.ps1 (with this computer's key, home router and ports filled in),
the device runtime (relaymcp-device.zip), the OpenSSH installer, and a double-tap launcher."""

from __future__ import annotations

import hashlib
import io
import json
import re
import shutil
import tarfile
import urllib.request
import zipfile
from pathlib import Path

import relaymcp

from . import config, sshconf

PACKAGE_DIR = Path(relaymcp.__file__).resolve().parent
TEMPLATE = PACKAGE_DIR / "device" / "setup" / "Relay-Setup.ps1"
MSI_NAME = "OpenSSH-Win64-v10.0.0.0.msi"
MSI_URL = f"https://github.com/PowerShell/Win32-OpenSSH/releases/download/10.0.0.0p2-Preview/{MSI_NAME}"
MSI_SHA256 = "ddec9c53864280759cf9f74791cefd387100e3946aa849a1c138a4ed1b96b7d9"
# The virtual-gamepad driver. vgamepad only ships as source, and building it on a machine without ViGEmBus opens the
# driver's interactive installer (which would hang an unattended setup), so the kit carries the driver's MSI and setup
# installs it silently first. It's the exact MSI vgamepad bundles, taken from its pinned source release on PyPI.
VIGEM_MSI = "ViGEmBusSetup_x64.msi"
VIGEM_SDIST_URL = "https://files.pythonhosted.org/packages/source/v/vgamepad/vgamepad-0.1.0.tar.gz"
VIGEM_SDIST_SHA256 = "57f6bd01aec0c172947517fb782d150ef9b285f7f4d524c317374fa5c24a89de"
VIGEM_MSI_MEMBER = "vgamepad-0.1.0/vgamepad/win/vigem/install/x64/ViGEmBusSetup_x64.msi"
VIGEM_MSI_SHA256 = "5abbba8a4a07aaaeb50b4666183b2f243e0e5ad288026d2a9f3595ed237c4b28"
DEVICE_ZIP = "relaymcp-device.zip"
SETUP_FILE = "Relay-Setup.ps1"
LAUNCHER = "Setup RelayMCP.cmd"
KIT_FILES = (SETUP_FILE, DEVICE_ZIP, MSI_NAME, VIGEM_MSI)

DEVICE_PYPROJECT = """\
# Generated by `relaymcp kit` (RelayMCP {version}): the device runtime, installed on the handheld with uv.
[project]
name = "relaymcp-device"
version = "{version}"
description = "RelayMCP device runtime for Windows handhelds: agent, hardware MCP server, voice prompts"
requires-python = ">=3.12,<3.13"
dependencies = [
{deps}
]

[project.scripts]
relaymcp-device = "relaymcp.device.server:main"

[project.gui-scripts]
relaymcp-ask = "relaymcp.device.launcher:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["relaymcp"]
"""


def device_requirements() -> list[str]:
    """The `device` extra of relaymcp: from this checkout's pyproject.toml when running from one (an editable install's
    metadata is only rewritten by a reinstall, so after a dependency change it would ship the old list and give the
    same code another build hash), else from the installed distribution's metadata."""
    pyproject = PACKAGE_DIR.parent.parent / "pyproject.toml"
    if pyproject.exists():
        m = re.search(r"^device\s*=\s*\[(.*?)^\]", pyproject.read_text(encoding="utf-8"), re.S | re.M)
        if m:
            return [s for s in re.findall(r'"([^"]+)"', m.group(1))]
    try:
        from importlib.metadata import PackageNotFoundError, requires
        reqs = requires("relaymcp") or []
        found = [r.split(";")[0].strip() for r in reqs if re.search(r"""extra\s*==\s*["']device["']""", r)]
        if found:
            return found
    except PackageNotFoundError:
        pass
    raise RuntimeError("couldn't find the device dependencies (pyproject.toml [project.optional-dependencies])")


def build_device_zip() -> bytes:
    """Deterministic zip (sorted names, fixed timestamps): the same code always gives the same hash, so re-running
    setup on the handheld skips the reinstall when nothing changed."""
    buf = io.BytesIO()
    deps = ",\n".join(f'    "{d}"' for d in device_requirements())
    host = PACKAGE_DIR / "host"  # the handheld never imports it; a host-only change mustn't look like a device update
    files = sorted(p for p in PACKAGE_DIR.rglob("*")
                   if p.is_file() and "__pycache__" not in p.parts and p.suffix not in (".pyc", ".pyo")
                   and not p.name.startswith(".") and not p.name.startswith("._") and host not in p.parents)
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        def add(name: str, data: bytes) -> None:
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            z.writestr(info, data)
        add("pyproject.toml", DEVICE_PYPROJECT.format(version=relaymcp.__version__, deps=deps).encode())
        for path in files:
            add("relaymcp/" + path.relative_to(PACKAGE_DIR).as_posix(), path.read_bytes())
    return buf.getvalue()


_PS_SINGLE_QUOTES = re.compile("(['\u2018\u2019\u201a\u201b])")


def ps_escape(value: str) -> str:
    """Escape text for a PowerShell single-quoted string. PowerShell also treats the typographic single quotes
    (\u2018 \u2019 \u201a \u201b) as quote characters, so they are doubled like the ASCII apostrophe."""
    return _PS_SINGLE_QUOTES.sub(r"\1\1", str(value))


def ps_quote(value: str) -> str:
    return "'" + ps_escape(value) + "'"


def ps_list(values: list[str]) -> str:
    return ", ".join(ps_quote(v) for v in values)


def render_setup(cfg: dict, host_ip: str | None, host_name: str | None) -> str:
    d, token, port = cfg["device"], config.ensure_token(cfg), cfg["enroll"]["port"]
    report = [f"http://{h}:{port}/done/{token}" for h in (host_ip, host_name) if h]
    values = {
        "__DEVICENAME__": d["name"],
        "__HOSTLABEL__": cfg.get("host_label") or config.default_host_label(),
        "__PUBKEYS__": ps_list([sshconf.public_key()]),
        "__NETWORKS__": ps_list(d.get("home_networks") or ["home"]),
        "__GATEWAYS__": ps_list(d.get("home_gateways") or []),
        "__REPORTURLS__": ps_list(report),
        "__SCREENPORT__": str(int(d["ports"]["screen"])),
        "__HARDWAREPORT__": str(int(d["ports"]["hardware"])),
        "__VOICEPORT__": str(int(d["ports"]["voice"])),
        "__WINDOWSMCP__": cfg.get("windows_mcp") or config.WINDOWS_MCP,
        "__VERSION__": relaymcp.__version__,
    }
    text = TEMPLATE.read_text(encoding="utf-8")
    for key in ("__DEVICENAME__", "__HOSTLABEL__", "__WINDOWSMCP__", "__VERSION__"):
        values[key] = ps_escape(values[key])  # these sit inside single-quoted strings
    for key, value in values.items():
        text = text.replace(key, value)
    left = sorted(set(re.findall(r"__[A-Z]+__", text)))
    if left:
        raise RuntimeError(f"unfilled placeholders in the setup template: {', '.join(left)}")
    return text


def fetch_msi() -> Path:
    config.CACHE_DIR.mkdir(parents=True, exist_ok=True)
    path = config.CACHE_DIR / MSI_NAME
    if not path.exists() or _sha256(path.read_bytes()) != MSI_SHA256:
        with urllib.request.urlopen(MSI_URL, timeout=60) as r:
            data = r.read()
        if _sha256(data) != MSI_SHA256:
            raise RuntimeError("the OpenSSH installer failed its SHA-256 check")
        path.write_bytes(data)
    return path


def fetch_vigembus() -> Path:
    config.CACHE_DIR.mkdir(parents=True, exist_ok=True)
    path = config.CACHE_DIR / VIGEM_MSI
    if path.exists() and _sha256(path.read_bytes()) == VIGEM_MSI_SHA256:
        return path
    with urllib.request.urlopen(VIGEM_SDIST_URL, timeout=60) as r:
        sdist = r.read()
    if _sha256(sdist) != VIGEM_SDIST_SHA256:
        raise RuntimeError("the vgamepad source release failed its SHA-256 check")
    with tarfile.open(fileobj=io.BytesIO(sdist), mode="r:gz") as tar:
        member = tar.extractfile(VIGEM_MSI_MEMBER)
        data = member.read() if member else b""
    if _sha256(data) != VIGEM_MSI_SHA256:
        raise RuntimeError("the ViGEmBus installer failed its SHA-256 check")
    path.write_bytes(data)
    return path


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def launcher_text(host_label: str) -> str:
    return (
        "@echo off\r\n"
        "rem Double-tap me on the handheld (from a USB drive, microSD card or a copied folder) and choose \"Yes\".\r\n"
        f"rem Sets up or repairs RelayMCP so your AI agent on {host_label} can control this handheld at home.\r\n"
        "powershell.exe -NoProfile -ExecutionPolicy Bypass -File \"%~dp0Relay-Setup.ps1\"\r\n"
    )


README_TXT = """RelayMCP setup kit for "{name}"
==============================

On the handheld (signed in, on your home network):
  1. Copy this folder to a USB drive or microSD card (or anywhere the handheld can open it).
  2. Double-tap "Setup RelayMCP.cmd" and choose Yes when Windows asks.

It installs OpenSSH Server (key-only, local network only), the RelayMCP agent and Windows-MCP, all switched on only
at home. Afterwards "Repair RelayMCP" on the handheld's Desktop re-runs it; everything is removed with:
  powershell -ExecutionPolicy Bypass -File C:\\ProgramData\\RelayMCP\\Relay-Setup.ps1 -Uninstall

Built by RelayMCP {version} on {host}. Docs: https://github.com/brennengreen/RelayMCP
"""


def build(cfg: dict, out_dir: Path | None = None, host_ip: str | None = None, host_name: str | None = None) -> Path:
    """Write the kit to out_dir (default ~/.relaymcp/kit/<device>) and return that folder."""
    out = Path(out_dir or config.KIT_DIR / cfg["device"]["name"])
    out.mkdir(parents=True, exist_ok=True)
    label = cfg.get("host_label") or config.default_host_label()
    (out / SETUP_FILE).write_bytes(render_setup(cfg, host_ip, host_name).replace("\r\n", "\n").replace("\n", "\r\n")
                                   .encode("utf-8-sig"))
    zip_bytes = build_device_zip()
    if not (out / DEVICE_ZIP).exists() or (out / DEVICE_ZIP).read_bytes() != zip_bytes:
        (out / DEVICE_ZIP).write_bytes(zip_bytes)
    shutil.copyfile(fetch_msi(), out / MSI_NAME)
    shutil.copyfile(fetch_vigembus(), out / VIGEM_MSI)
    (out / LAUNCHER).write_bytes(launcher_text(label).encode("ascii", "replace"))
    (out / "README.txt").write_text(README_TXT.format(name=cfg["device"]["name"], version=relaymcp.__version__,
                                                      host=label), encoding="utf-8")
    (out / "kit.json").write_text(json.dumps({"version": relaymcp.__version__, "device": cfg["device"]["name"],
                                              "zip_sha256": _sha256(zip_bytes)}, indent=1), encoding="utf-8")
    return out
